stages:
  - lint
  - build
  - test
  - deploy

variables:
  NODE_ENV: "test"

lint:
  stage: lint
  image: node:18
  script:
    - cd api && npm ci && npm run lint
    - cd ../web/kassy-kube && npm ci && npm run lint
  allow_failure: true

build:
  stage: build
  image: node:18
  script:
    - cd api && npm ci && npm run build
    - cd ../web/kassy-kube && npm ci && npm run build
  artifacts:
    paths:
      - api/dist/
      - web/kassy-kube/dist/

test_unit:
  stage: test
  image: node:18
  script:
    - cd api && npm ci && npm test

deploy_vercel:
  stage: deploy
  image: node:18
  only:
    - main
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod --yes
